### ISSUE TITLE
depending on core pulls in a _lot_ of dependencies

### ISSUE THREAD

**Issue by UnixJunkie** [SGrondin/tdigest#3]
Way too much in fact...
Can't you rely on something with a smaller footprint?

**Comment by SGrondin** [comment]
I spent a day last weekend trying the library without Core. Performance dropped by about 11x.
I think in a few weeks I'll reimplement the dozen or so parts of Core that I need, but for now the performance drop is too extreme to ignore

**Comment by UnixJunkie** [comment]
I was not suggesting to rewrite the parts that you need.
Maybe, rely on Core_kernel or something like that with a smaller footprint.
If you do really need the whole Core, then so be it.
Don't waste your time because of my remark.

**Comment by SGrondin** [comment]
Core_kernel doesn't exist anymore. The Unix parts of Core were moved out to Core_unix. Since the last year or two, Core is smaller and it plays the role of the old Core_kernel. There's also the smaller Base but it doesn't contain the features of Core that I need to make this library truly performant, so for now I have to use Core until I can extract the parts I rely on.
I'll close this issue for now, but I'll @ you when I release a future version that doesn't rely on Core.

**Comment by SGrondin** [comment]
This library now depends on Base instead of Core, greatly reducing the number of transitive dependencies.

**Comment by UnixJunkie** [comment]
Merci, vous etes un chamelier de hot vol!

**Comment by SGrondin** [comment]
high flying camelier? I'll take it! 😄
